# Generated by Django 3.0.8 on 2020-09-19 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_collection', '0003_playlist_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='artists',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='song',
        ),
        migrations.AddField(
            model_name='playlist',
            name='song',
            field=models.ManyToManyField(to='music_collection.Song'),
        ),
    ]
