# Generated by Django 3.0.8 on 2020-09-19 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_collection', '0004_auto_20200919_2320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='song',
        ),
    ]
