# Generated by Django 3.0.8 on 2020-09-19 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_collection', '0005_remove_playlist_song'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlayList',
            new_name='UserPlaylist',
        ),
        migrations.RenameField(
            model_name='userplaylist',
            old_name='name',
            new_name='playlist_name',
        ),
    ]
