# Generated by Django 3.0.8 on 2020-09-19 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_collection', '0006_auto_20200920_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='userplaylist',
            name='song',
            field=models.ManyToManyField(to='music_collection.Song'),
        ),
    ]
