# Generated by Django 3.0.8 on 2020-09-16 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music_collection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Song name')),
                ('cover_img', models.ImageField(upload_to='song_cover_img')),
                ('song', models.FileField(upload_to='song_directory_path')),
                ('genre', models.CharField(choices=[('Rock', 'Rock'), ('pop', 'pop'), ('hip hop', 'hip,hop'), ('country', 'country'), ('classical', 'classcical')], max_length=100)),
                ('artists', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_collection.Artist')),
            ],
        ),
    ]
